# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/testrepo',
                'doc_host': 'https://amaiya.github.io',
                'git_url': 'https://github.com/amaiya/testrepo',
                'lib_path': 'testrepo'},
  'syms': {'testrepo.core': {'testrepo.core.foo': ('core.html#foo', 'testrepo/core.py')}}}
